import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:kairo/core/components/components.dart';
import 'package:kairo/core/theme/theme.dart';
import 'package:kairo/core/utils/utils.dart';
import 'package:kairo/features/allocation/domain/entities/allocation_category.dart';
import 'package:kairo/features/allocation/presentation/providers/allocation_providers.dart';
import 'package:kairo/features/auth/presentation/providers/auth_providers.dart';

/// Category management screen for customizing allocation categories (FR3)
class CategoryManagementScreen extends ConsumerWidget {
  const CategoryManagementScreen({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final categoriesAsync = ref.watch(allocationCategoriesProvider);

    return Scaffold(
      appBar: AppBar(
        title: const Text('Manage Categories'),
        centerTitle: true,
      ),
      body: categoriesAsync.when(
        data: (categories) => _buildCategoryList(context, ref, categories),
        loading: () => const LoadingIndicator(),
        error: (error, stack) => ErrorView.generic(
          message: 'Failed to load categories: $error',
        ),
      ),
      floatingActionButton: FloatingActionButton.extended(
        onPressed: () => _showAddCategoryDialog(context, ref),
        icon: const Icon(Icons.add),
        label: const Text('Add Category'),
      ),
    );
  }

  Widget _buildCategoryList(
    BuildContext context,
    WidgetRef ref,
    List<AllocationCategory> categories,
  ) {
    if (categories.isEmpty) {
      return EmptyState.noItems(
        itemName: 'categories',
        onAction: () => _showAddCategoryDialog(context, ref),
      );
    }

    return ReorderableListView.builder(
      padding: const EdgeInsets.all(AppSizes.paddingMedium),
      itemCount: categories.length,
      onReorder: (oldIndex, newIndex) {
        _reorderCategories(ref, categories, oldIndex, newIndex);
      },
      itemBuilder: (context, index) {
        final category = categories[index];
        return _CategoryTile(
          key: ValueKey(category.id),
          category: category,
          onEdit: () => _showEditCategoryDialog(context, ref, category),
          onDelete: () => _confirmDeleteCategory(context, ref, category),
        );
      },
    );
  }

  void _showAddCategoryDialog(BuildContext context, WidgetRef ref) {
    showDialog(
      context: context,
      builder: (context) => _CategoryDialog(
        title: 'Add Category',
        onSave: (name, color, icon) async {
          final currentUser = await ref.read(currentUserProvider.future);
          if (currentUser == null) return;

          final categories = await ref.read(allocationCategoriesProvider.future);
          final maxOrder = categories.isEmpty
              ? 0
              : categories.map((c) => c.displayOrder).reduce((a, b) => a > b ? a : b);

          final newCategory = AllocationCategory(
            id: '', // Will be generated by database
            userId: currentUser.id,
            name: name,
            color: color,
            icon: icon,
            isDefault: false,
            displayOrder: maxOrder + 1,
            createdAt: DateTime.now(),
            updatedAt: DateTime.now(),
          );

          await ref.read(createCategoryProvider.notifier).execute(newCategory);
        },
      ),
    );
  }

  void _showEditCategoryDialog(
    BuildContext context,
    WidgetRef ref,
    AllocationCategory category,
  ) {
    showDialog(
      context: context,
      builder: (context) => _CategoryDialog(
        title: 'Edit Category',
        initialName: category.name,
        initialColor: category.color,
        initialIcon: category.icon,
        onSave: (name, color, icon) async {
          final updatedCategory = category.copyWith(
            name: name,
            color: color,
            icon: icon,
            updatedAt: DateTime.now(),
          );

          await ref.read(updateCategoryProvider.notifier).execute(updatedCategory);
        },
      ),
    );
  }

  void _reorderCategories(
    WidgetRef ref,
    List<AllocationCategory> categories,
    int oldIndex,
    int newIndex,
  ) {
    // Adjust newIndex if needed (ReorderableListView quirk)
    if (newIndex > oldIndex) {
      newIndex--;
    }

    // Create a new list with reordered categories
    final reordered = List<AllocationCategory>.from(categories);
    final movedCategory = reordered.removeAt(oldIndex);
    reordered.insert(newIndex, movedCategory);

    // Save the new order to database
    ref.read(reorderCategoriesProvider.notifier).execute(reordered);
  }

  void _confirmDeleteCategory(
    BuildContext context,
    WidgetRef ref,
    AllocationCategory category,
  ) {
    showDialog(
      context: context,
      builder: (context) => AlertDialog(
        title: const Text('Delete Category'),
        content: Text(
          'Are you sure you want to delete "${category.name}"?\n\nThis action cannot be undone.',
        ),
        actions: [
          TextButton(
            onPressed: () => Navigator.of(context).pop(),
            child: const Text('Cancel'),
          ),
          FilledButton(
            onPressed: () async {
              Navigator.of(context).pop();
              await ref.read(deleteCategoryProvider.notifier).execute(category.id);

              if (context.mounted) {
                context.showSuccessSnackBar('${category.name} deleted');
              }
            },
            style: FilledButton.styleFrom(
              backgroundColor: AppColors.error,
            ),
            child: const Text('Delete'),
          ),
        ],
      ),
    );
  }
}

class _CategoryTile extends StatelessWidget {
  final AllocationCategory category;
  final VoidCallback onEdit;
  final VoidCallback onDelete;

  const _CategoryTile({
    super.key,
    required this.category,
    required this.onEdit,
    required this.onDelete,
  });

  @override
  Widget build(BuildContext context) {
    final categoryColor = AppColors.fromHex(category.color);
    return Card(
      margin: const EdgeInsets.only(bottom: AppSizes.paddingSmall),
      child: ListTile(
        leading: CircleAvatar(
          backgroundColor: categoryColor.withValues(alpha: 0.2),
          child: Icon(
            _getIconData(category.icon),
            color: categoryColor,
          ),
        ),
        title: Text(
          category.name,
          style: Theme.of(context).textTheme.titleMedium?.copyWith(
                fontWeight: FontWeight.w600,
              ),
        ),
        subtitle: Text(
          category.isDefault ? 'Default category' : 'Custom category',
          style: Theme.of(context).textTheme.bodySmall,
        ),
        trailing: Row(
          mainAxisSize: MainAxisSize.min,
          children: [
            IconButton(
              icon: const Icon(Icons.edit),
              onPressed: onEdit,
              tooltip: 'Edit category',
            ),
            if (!category.isDefault) // Can't delete default categories
              IconButton(
                icon: const Icon(Icons.delete, color: AppColors.error),
                onPressed: onDelete,
                tooltip: 'Delete category',
              ),
          ],
        ),
      ),
    );
  }

  IconData _getIconData(String? iconName) {
    switch (iconName) {
      case 'family':
        return Icons.family_restroom;
      case 'emergency':
        return Icons.warning_amber;
      case 'savings':
        return Icons.savings;
      case 'daily':
        return Icons.shopping_cart;
      case 'community':
        return Icons.people;
      default:
        return Icons.category;
    }
  }
}

class _CategoryDialog extends StatefulWidget {
  final String title;
  final String? initialName;
  final String? initialColor;
  final String? initialIcon;
  final Function(String name, String color, String? icon) onSave;

  const _CategoryDialog({
    required this.title,
    this.initialName,
    this.initialColor,
    this.initialIcon,
    required this.onSave,
  });

  @override
  State<_CategoryDialog> createState() => _CategoryDialogState();
}

class _CategoryDialogState extends State<_CategoryDialog> {
  late final TextEditingController _nameController;
  late String _selectedColor;
  String? _selectedIcon;

  final List<String> _colorOptions = [
    '#EF4444', // Red
    '#F97316', // Orange
    '#F59E0B', // Amber
    '#10B981', // Green
    '#3B82F6', // Blue
    '#8B5CF6', // Purple
    '#EC4899', // Pink
    '#6B7280', // Gray
  ];

  @override
  void initState() {
    super.initState();
    _nameController = TextEditingController(text: widget.initialName);
    _selectedColor = widget.initialColor ?? _colorOptions.first;
    _selectedIcon = widget.initialIcon;
  }

  @override
  void dispose() {
    _nameController.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return AlertDialog(
      title: Text(widget.title),
      content: SingleChildScrollView(
        child: Column(
          mainAxisSize: MainAxisSize.min,
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            AppTextField(
              controller: _nameController,
              label: 'Category Name',
              prefixIcon: Icons.label,
              autofocus: true,
            ),
            const SizedBox(height: AppSizes.paddingMedium),
            Text(
              'Color',
              style: Theme.of(context).textTheme.titleSmall,
            ),
            const SizedBox(height: AppSizes.paddingSmall),
            Wrap(
              spacing: AppSizes.paddingSmall,
              runSpacing: AppSizes.paddingSmall,
              children: _colorOptions.map((color) {
                final isSelected = color == _selectedColor;
                return InkWell(
                  onTap: () {
                    setState(() {
                      _selectedColor = color;
                    });
                  },
                  child: Container(
                    width: 40,
                    height: 40,
                    decoration: BoxDecoration(
                      color: AppColors.fromHex(color),
                      shape: BoxShape.circle,
                      border: Border.all(
                        color: isSelected ? Theme.of(context).colorScheme.onSurface : Colors.transparent,
                        width: 3,
                      ),
                    ),
                    child: isSelected
                        ? Icon(Icons.check, color: Theme.of(context).colorScheme.surface, size: 20)
                        : null,
                  ),
                );
              }).toList(),
            ),
          ],
        ),
      ),
      actions: [
        TextButton(
          onPressed: () => Navigator.of(context).pop(),
          child: const Text('Cancel'),
        ),
        FilledButton(
          onPressed: () {
            final name = _nameController.text.trim();
            if (name.isEmpty) return;

            widget.onSave(name, _selectedColor, _selectedIcon);
            Navigator.of(context).pop();
          },
          child: const Text('Save'),
        ),
      ],
    );
  }
}
